name: Deploy to Render

on:
  workflow_run:
    workflows: ["CI Pipeline with security"]
    # When CI pipeline runs correctly it starts
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Build, Push and deploy to Render
    runs-on: ubuntu-24.04
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v5

      # Step 2: Set up Python environment (version 3.12)
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      # Step 3: Generate image tag for docker    
      - name: Generate Image Tag
        id: image_tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Step 4: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 5: Login to Docker hub with credentials
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #Step 6: Build an Push Docker Image to repository
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/images/Dockerfile.render
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPO }}:${{ steps.image_tag.outputs.tag }}, ${{ secrets.DOCKER_HUB_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      #Step 7: Deploy on Render
      - name: Deploy to Render using Deploy Hook
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_WEBHOOK }}
        run: |
          echo "Triggering Render deployment..."
          curl "$deploy_url"